version: '3.8'
services:
  sweb:
    container_name: servWeb
    build: 
      context: ./domenicaSweb
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=dome
      - PASSWD=1234
      - HOSTNAME=domenicaSweb.asir.es
    networks: 
      netasir:
          ipv4_address: 179.124.10.2 
  sbd:
    container_name: servBD
    build: 
      context: ./domenicaSBD
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=dome
      - PASSWD=1234
      - HOSTNAME=domenicaSBD.asir.es
    networks: 
      netasir:
          ipv4_address: 179.124.10.3 
networks: 
  netasir:
      ipam: 
          driver: default
          config: 
              - subnet: 179.124.10.0/24